### ISSUE TITLE
`PrecisionTo` doesn't follow capitalization conventions

### ISSUE THREAD

**Issue by garciadelcastillo** [RobotExMachina/Machina-Python#1]
https://github.com/RobotExMachina/Machina-Python/blob/75c54b6e17d1a6845aa254960dbb4c6828f0ac76/machina_for_python/machinaRobot.py#L147

Either refactor to `precisionTo` or camelcase the rest of the API?

**Comment by Ardibid** [comment]
Thanks, @garciadelcastillo. This function and a few others have been modified to reflect camelCase format.
